# Generated by Django 5.2 on 2025-05-07 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
    ]
